/* one-off v3: radial triangle partition + safe child ordering */
const fs = require("fs");
let src = fs.readFileSync("js/effects.js", "utf8");
const start = src.indexOf("/* generic rigger v2:");
const anchor = "function _box(g, w, h, d, mat, x, y, z, rx) {";
const end = src.indexOf(anchor);
if (start < 0 || end < start) throw new Error("markers missing");

const L = [
  "/* generic rigger v3:",
  " *  • oversized merged meshes split per-triangle to nearest hub",
  " *  • each assembled wheel partitions its parts by RADIAL DISTANCE:",
  " *    triangles within the tire radius go into the spinning group;",
  " *    lumpier bits (calipers, fender arcs) become steer-only statics",
  " *    parked at child index >= 2 so game.js never rotates them",
  " *  • output ordered [FL,FR,RL,RR]; fronts only receive steering     */",
  "function rigWheelsGeneric(group, hubs, spec, reg) {",
  "  const spinBy = { FL: [], FR: [], RL: [], RR: [] };",
  "  const raw = [];",
  "  group.traverse(o => {",
  "    if (!o.isMesh) return;",
  "    const kind = reg.match(o);",
  "    if (kind === \"spin\") raw.push({ mesh: o, kind });",
  "  });",
  "",
  "  const wheelDia = spec.wheelRadius * 2.2;",
  "  let rr = 0;",
  "  const R = spec.wheelRadius;",
  "",
  "  /* move one already-localised mesh into the corner, splitting its",
  "   * triangles between a spinning core and a steer-only outer shell */",
  "  function mountCorner(ck, mesh) {",
  "    const wg = new THREE.Group();",
  '    wg.name = "cwm_wheel_" + ck;',
  "    wg.position.set(hubs[ck][0], hubs[ck][1], hubs[ck][2]);",
  "    const spin = new THREE.Group();",
  "    const shell = new THREE.Group();      // children[1]: never spun",
  "    wg.add(spin);",
  "    wg.add(shell);",
  "    mesh.geometry.translate(-wg.position.x, -wg.position.y, -wg.position.z);",
  "    const pos = mesh.geometry.attributes.position;",
  "    const nor = mesh.geometry.attributes.normal;",
  "    const idx = mesh.geometry.index;",
  "    const triCount = Math.floor((idx ? idx.count : pos.count) / 3);",
  "    const gi = i => (idx ? idx.getX(i) : i);",
  "    const core = { pos: [], nor: [] };",
  "    const rim  = { pos: [], nor: [] };",
  "    const maxR = spec.wheelRadius * 1.18;",
  "    for (let t = 0; t < triCount; t++) {",
  "      let rT = 0;",
  "      for (let k = 0; k < 3; k++) {",
  "        const id = gi(t * 3 + k);",
  "        rT = Math.max(rT, Math.hypot(pos.getY(id), pos.getZ(id)));",
  "      }",
  "      const dst = rT <= maxR ? core : rim;",
  "      for (let k = 0; k < 3; k++) {",
  "        const id = gi(t * 3 + k);",
  "        dst.pos.push(pos.getX(id), pos.getY(id), pos.getZ(id));",
  "        if (nor) dst.nor.push(nor.getX(id), nor.getY(id), nor.getZ(id));",
  "      }",
  "    }",
  "    const mk = buf => {",
  "      if (!buf.pos.length) return null;",
  "      const ng = new THREE.BufferGeometry();",
  '      ng.setAttribute("position", new THREE.Float32BufferAttribute(buf.pos, 3));',
  "      if (buf.nor.length === buf.pos.length)",
  '        ng.setAttribute("normal", new THREE.Float32BufferAttribute(buf.nor, 3));',
  "      ng.computeVertexNormals();",
  "      const mm = new THREE.Mesh(ng, mesh.material);",
  "      mm.castShadow = mesh.castShadow;",
  "      return mm;",
  "    };",
  "    const coreM = mk(core);",
  "    if (coreM) spin.add(coreM);",
  "    const rimM = mk(rim);",
  "    if (rimM) shell.add(rimM);",
  "    group.add(wg);",
  "    return wg;",
  "  }",
  "",
  "  /* phase 1: classify raw meshes into corners */",
  "  const cornerMeshes = { FL: [], FR: [], RL: [], RR: [] };",
  "  for (const item of raw) {",
  "    item.mesh.geometry.computeBoundingBox();",
  "    const c = new THREE.Vector3(); item.mesh.geometry.boundingBox.getCenter(c);",
  "    const ck = cornerOfName(item.mesh.name) || nearestHub(hubs, c.x, c.z);",
  "    cornerMeshes[ck].push(item.mesh);",
  "    group.remove(item.mesh);",
  "  }",
  "",
  "  /* phase 2: mount each corner, splitting radial core vs outer shell */",
  "  const wheels = [];",
  "  for (const ck of CORNER_KEYS) {",
  "    const list = cornerMeshes[ck];",
  "    if (!list.length) continue;",
  "    // merge multiple meshes of the same corner by mounting them into",
  "    // one shared wheel group sequentially",
  "    let wg = null;",
  "    for (const mesh of list) {",
  "      wg = mountCorner(ck, mesh);",
  "    }",
  "    wheels.push(wg);",
  "  }",
  ""
];
fs.writeFileSync("js/effects.js", src.slice(0, start) + L.join("\n") + "\n" + src.slice(end));
console.log("rigger v3 installed");
