/* one-off v3b: shared wheel group per corner */
const fs = require("fs");
let src = fs.readFileSync("js/effects.js", "utf8");
const start = src.indexOf("/* generic rigger v3:");
const anchor = "function _box(g, w, h, d, mat, x, y, z, rx) {";
const end = src.indexOf(anchor);
if (start < 0 || end < start) throw new Error("markers missing");

const L = [
  "/* generic rigger v3:",
  " *  • oversized merged meshes split per-triangle to nearest hub",
  " *  • radial partition: triangles within tire radius SPIN; lumpier",
  " *    outer bits become steer-only statics (never rotated by game)",
  " *  • output ordered [FL,FR,RL,RR]; fronts only receive steering     */",
  "function rigWheelsGeneric(group, hubs, spec, reg) {",
  "  const raw = [];",
  "  group.traverse(o => {",
  "    if (!o.isMesh) return;",
  "    const kind = reg.match(o);",
  '    if (kind === "spin") raw.push({ mesh: o, kind });',
  "  });",
  "",
  "  const R = spec.wheelRadius;",
  "",
  "  /* phase 1: classify raw meshes into corners */",
  "  const cornerMeshes = { FL: [], FR: [], RL: [], RR: [] };",
  "  for (const item of raw) {",
  "    item.mesh.geometry.computeBoundingBox();",
  "    const c = new THREE.Vector3(); item.mesh.geometry.boundingBox.getCenter(c);",
  "    const ck = cornerOfName(item.mesh.name) || nearestHub(hubs, c.x, c.z);",
  "    cornerMeshes[ck].push(item.mesh);",
  "    group.remove(item.mesh);",
  "  }",
  "",
  "  /* phase 2: mount each corner into a single shared wheel group */",
  "  const wheels = [];",
  "  const wheelByCorner = {};",
  "  for (const ck of CORNER_KEYS) {",
  "    const list = cornerMeshes[ck];",
  "    if (!list.length) continue;",
  "    const wg = new THREE.Group();",
  '    wg.name = "cwm_wheel_" + ck;',
  "    wg.position.set(hubs[ck][0], hubs[ck][1], hubs[ck][2]);",
  "    const spin = new THREE.Group();",
  "    const shell = new THREE.Group();      // children[1]: never spun",
  "    wg.add(spin);",
  "    wg.add(shell);",
  "    wheelByCorner[ck] = { wg, spin, shell };",
  "  }",
  "  for (const ck of CORNER_KEYS) {",
  "    const slot = wheelByCorner[ck];",
  "    if (!slot) continue;",
  "    for (const mesh of cornerMeshes[ck]) {",
  "      mesh.geometry.translate(-slot.wg.position.x, -slot.wg.position.y, -slot.wg.position.z);",
  "      const pos = mesh.geometry.attributes.position;",
  "      const nor = mesh.geometry.attributes.normal;",
  "      const idx = mesh.geometry.index;",
  "      const triCount = Math.floor((idx ? idx.count : pos.count) / 3);",
  "      const gi = i => (idx ? idx.getX(i) : i);",
  "      const maxR = spec.wheelRadius * 1.18;",
  "      const core = { pos: [], nor: [] };",
  "      const rim  = { pos: [], nor: [] };",
  "      for (let t = 0; t < triCount; t++) {",
  "        let rT = 0;",
  "        for (let k = 0; k < 3; k++) {",
  "          const id = gi(t * 3 + k);",
  "          rT = Math.max(rT, Math.hypot(pos.getY(id), pos.getZ(id)));",
  "        }",
  "        const dst = rT <= maxR ? core : rim;",
  "        for (let k = 0; k < 3; k++) {",
  "          const id = gi(t * 3 + k);",
  "          dst.pos.push(pos.getX(id), pos.getY(id), pos.getZ(id));",
  "          if (nor) dst.nor.push(nor.getX(id), nor.getY(id), nor.getZ(id));",
  "        }",
  "      }",
  "      const mk = b => {",
  "        if (!b.pos.length) return null;",
  "        const ng = new THREE.BufferGeometry();",
  '        ng.setAttribute("position", new THREE.Float32BufferAttribute(b.pos, 3));',
  "        if (b.nor.length === b.pos.length)",
  '          ng.setAttribute("normal", new THREE.Float32BufferAttribute(b.nor, 3));',
  "        ng.computeVertexNormals();",
  "        const mm = new THREE.Mesh(ng, mesh.material);",
  "        mm.castShadow = mesh.castShadow;",
  "        return mm;",
  "      };",
  "      const coreM = mk(core);",
  "      if (coreM) slot.spin.add(coreM);",
  "      const rimM = mk(rim);",
  "      if (rimM) slot.shell.add(rimM);",
  "    }",
  "    wheels.push(slot.wg);",
  "  }",
  ""
];
fs.writeFileSync("js/effects.js", src.slice(0, start) + L.join("\n") + "\n" + src.slice(end));
console.log("rigger v3b installed");
